Added additional options to form dropdowns "Technology" and "Library Type"
UofS-Pulse-Binfo/lims_rawseq pull request #23
Opened 2024-03-08 17:30 UTC by carolyncaron

**Issue #22**

## Motivation

As requested by Rob, 3 additional options were needed in the form dropdowns in order to enter new sequencing runs. Specifically:
**Sequencing Technology**: Illumina NovaSeq6000, Pacbio Revio
**Library Type**: CRISPRclean Ribosomal RNA Depletion (Jumpcode Genomics)

## What does this PR do?

Adds the above options to the appropriate hard-coded form arrays in the lims.module file, just as I did in Issue #21 for an older request to add an option to the **Sequence Technology** dropdown

## Testing

### Manual Testing
1. Clone this repository and switch to the branch for this PR: `git checkout 22-addTechLibraryOptions`
2. Setup a KPclone by following the instructions for `Local Clone for Module Development` and mount this repo you just cloned: `lims_rawseq`
3. Go to your new KPclone site and login with your KnowPulse credentials
4. Go to the right-hand sidebar and choose `"Add Sequencing Run"` from the list (the 5th option in the list)
5. On the form, check "Library Type" and make sure **CRISPRclean Ribosomal RNA Depletion (Jumpcode Genomics)** is there
6. Check "Sequencing Technology" and make sure BOTH **Illumina NovaSeq6000** and **Pacbio Revio** are in the list

2024-03-12 22:26 UTC, ruobinLiu requested changes, later dismissed
We went to create a random sequence run, I confirm the new items are selectable from the drop down. However, we we tried to save it, we encountered an unexpected error :( Please try again later.

2024-03-12 22:35 UTC, carolyncaron commented
Thanks Ruobin! I looked at the logs and there is in fact a PDOException 😢 Here is the output for my own reference:

> PDOException: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(30): INSERT INTO lims_seqrun (nid, run_name, filename, md5sum, library_type, insert_length, fragment_length, index_type, technology, read_type, description, sample_id) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11); Array ( ) in drupal_write_record() (line 7538 of /var/www/html/includes/common.inc).

2024-03-13 21:45 UTC, carolyncaron commented
I've made a change to update the character limit for the "Library Type" dropdown from 30 to 100, since the new option that broke the form was 50 characters long. To see the change take effect, there is an extra step needed during testing to update the underlying schema in KP clone. The new steps for testing also reflect using `Local Clone for data testing` steps rather than for module development since that is the more ideal way.

### New manual testing instructions

1. Setup a KPclone by following the instructions for `Local Clone for data testing`
2. Access your new container through the terminal using: `docker exec -it CONTAINERNAME bash`
3. Navigate to the custom modules directory in your clone: `cd sites/all/modules/custom/` and remove the existing lims module directory: `rm -r lims`
4. Now clone the repository: `git clone https://github.com/UofS-Pulse-Binfo/lims_rawseq.git lims`
5. Change into the directory: `cd lims` then checkout this PR's branch: `git checkout 22-addTechLibraryOptions`
6. Now open your KP clone in the browser and login with your KP credentials
7. In the URL, after localhost/ (if you specified a port when you created the container, go after the slash after the port number. Ex: `localhost:8880/`) and add `update.php`. For example: `localhost/update.php`
8. Follow the instructions on the page and make sure you see an update called `lims_update_7005` (Note: You may see a number of warnings at the end, but from what I can tell, they are all from other modules and hopefully will be dealt with during the T4 upgrade) 
9. Now go back to your homepage and navigate to the page for adding a Sequencing Run (Or navigate through the URL, for example: `localhost/node/add/seq-run`)
10. Fill out the required fields in the form, and for the "Library Type" dropdown, select **CRISPRclean Ribosomal RNA Depletion (Jumpcode Genomics)** (NOTE: Germplasm name autocomplete field is required despite missing an asterix)
11. Submit the form and confirm the new run was created!

2024-03-14 18:06 UTC, ruobinLiu commented
Thank you for the change! I have successfully created a Test Run, which I am able to find the **CRISPRclean Ribosomal RNA Depletion (Jumpcode Genomics)** under "Library Type" dropdown; as well as being able to find **Illumina NovaSeq6000** under "Technology" dropdown. Great job 🎉 
![Screenshot 2024-03-14 at 12 04 53 PM](https://github.com/UofS-Pulse-Binfo/lims_rawseq/assets/45402954/e901a8e9-e544-4861-bb64-6aedbd68b0a3)

2024-03-14 21:29 UTC, laceysanderson approved these changes

2024-03-14 21:30 UTC, merged